---
title: "ma132_enrollment"
output: html_notebook
author: "Marco Camalich"
---
```{r}
library(nycflights13)
library(tidyverse)
library(janitor)
library(dplyr)
library(ggplot2)
library(here)
library(skimr)
```

```{r}
df_cu=read_csv(here("data_raw","CU_ACAD_DEPT_WHEN_OFF_ENRL.csv ")) |> clean_names()
```
```{r}
df_cu
```
```{r}
skimr::skim(df_cu)
```
```{r}
df_calc=df_cu |>
  select(-acad_org,-title,-current_status,-course_id) |>
  filter(subject=="MA",
         catalog %in% c(125,131,132),
         component=="LEC")
df_calc
```

```{r}
df_pred = df_cu |> 
  filter(subject=="MA") |>
  select(-acad_org,-current_status,-course_id,-title) |>
  filter(component=="LEC", catalog %in% c(131,132) ) |>
  mutate(catalog=as.character(catalog)) |>
  separate_wider_delim(term_8," ",names = c("semester", "yr")) |>
  filter(!(semester=="Summer")) |>
  select(-subject) |>
  mutate(ay=((term_7-4000)/10) |> round()) |>
  select(-term_7,-yr,-component) |>
  slice_head(n=1,by=c("catalog","section","semester","ay"))|>
  select(-instructor) |>
  summarise(tot_enrl = sum(tot_enrl), .by=c("catalog","semester","ay")) |>
  pivot_wider(id_cols = ay,names_from = c("semester","catalog"),values_from = tot_enrl) |>
  clean_names() |>
  select(-spring_131)
  
df_pred
```
```{r}
ggplot(df_pred, aes(x = ay)) +
  geom_line(aes(y = fall_131, color = "Fall 131")) +
  geom_line(aes(y = fall_132, color = "Fall 132")) +
  geom_line(aes(y = spring_132, color = "Spring 132")) +
  labs(x = "Academic Year", y = "Total Enrollment", 
       title = "Enrollment Trends for Fall 131 and Fall 132") +
  scale_color_manual(values = c("Fall 131" = "blue", "Fall 132" = "red", "Spring 132" = "yellow")) +
  theme_minimal()
```

